[package]
name = "cryptochain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4.3"
hex-literal = "1.0.0"
sha3 = "0.10.8"

[dev-dependencies]
pretty_assertions = "1.4.1"
